name: CI

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

  pull_request:

  merge_group:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: install dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Build
        run: bun run build

  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Check Types
        run: bun check-types

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bun commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bun commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  cspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Check Spelling
        run: bun spell-check

  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Run EditorConfig Checker
        run: bun ec

  i18n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Extract and check translations
        run: |
          bun run --cwd packages/i18n i18n:extract
          bun lint:fix
          git diff --quiet --ignore-submodules HEAD

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Lint
        run: bun lint

  syncpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Run syncpack
        run: bun syncpack lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Test
        run: bun run test
